# Generated by manual edit on 2026-05-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(blank=True, max_length=200)),
                ("email", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("section", models.CharField(blank=True, max_length=80)),
                ("order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["order", "name"]},
        ),
    ]
