# Generated by Django 5.0.14 on 2026-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='section',
            field=models.CharField(blank=True, help_text='Optional section like Leadership, Operations', max_length=80),
        ),
    ]
